name: repository-secret-action
description: Encrypts and stores a secret on a repository

inputs:
  secret-name:
    description: The name of the secret that you want to create/update on the repository
    required: true

  secret-value:
    description: The value the secret to be set
    required: true

  github-token:
    description: A Personal Accedd Token with admin scope and repo scope to retrieve the public key and store the secret
    required: true

  repository:
    description: The repository to save/update the secret on in the form "owner/repository-name"

runs:
  using: node12
  main: dist/index.js
