name: Test Save Secret

on:
  workflow_dispatch:

jobs:
  test:
    name: Test Action
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Save Secret
        uses: ./
        with:
          github-token: ${{ secrets.PAT_WITH_SECRETS_ACCESS }}
          secret-name: test
          secret-value: hello world

